---
kind: pipeline
type: docker
name: production

steps:
- name: build
  image: alpine
  volumes:
  - name: mura.io
    path: /mura.io
  commands:
  - cd mura.io
  - ls

volumes:
- name: mura.io
  host:
    path: /var/www/mura.io
...