---
kind: pipeline
type: docker
name: production

steps:
- name: build
  image: alpine
  volumes:
  - name: mura
    path: /mura
  commands:
  - ls
  - cd mura
  - ls

volumes:
- name: mura
  host:
    path: /var/www/mura.io
...