---
kind: pipeline
type: docker
name: production

steps:
  - name: build
    image: node
    volumes:
      - name: mura
        path: /mura
    commands:
      - npm install
      - npm run build
      - rm -rf mura/
      - cd dist
      - cp -r * /mura/
      - cd /mura
      - ls

volumes:
  - name: mura
    host:
      path: /var/www/mura.io
